name: Draft release

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'README.md'
      - '.github/**/*.yml'

jobs:
  this:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
